#!/usr/bin/env sh

# HOSTNAME is exported via ~/.profile
# it's used in other scripts so no need to repopulate it here

echo "Backing up ${HOME}"
restic --password-command "pass Hosting/bups/$HOSTNAME" -r "$HOME/Backups/$HOSTNAME" backup "$HOME" --exclude-file "$HOME/.config/restic/excludes"
restic --password-command "pass Hosting/bups/$HOSTNAME" -r "$HOME/Backups/$HOSTNAME" forget --keep-daily 7 --keep-weekly 4 --keep-monthly 3 --keep-yearly 1 --prune

# server
echo "Backing up ${HOME}/Pictures"
restic --password-command "pass Hosting/bups/$HOSTNAME" -r /mnt/backups/pictures backup "$HOME/Pictures"
restic --password-command "pass Hosting/bups/$HOSTNAME" -r /mnt/backups/st forget --keep-daily 7 --keep-weekly 4 --keep-monthly 3 --keep-yearly 1 --prune

#for vm in 100 102 103 105 107 #101 104
#do
#    echo "Backing up $vm"
#    find "$HOME/Backups/dump" -regex ".*$vm.*" -print0 > "/tmp/backup_$vm"
#    restic --password-command "pass Hosting/bups/$HOSTNAME" -r /mnt/backups/st-"$vm" backup --files-from-raw /tmp/backup_$vm
#    restic --password-command "pass Hosting/bups/$HOSTNAME" -r /mnt/backups/st-"$vm" forget --keep-daily 1 --keep-weekly 4 --keep-monthly 3 --keep-yearly 1 --prune
#done
