#!/usr/bin/env sh
set -e

# HOSTNAME is exported via ~/.profile
# it's used in other scripts so no need to repopulate it here

. "$HOME/.config/openstack/gec-restic"
export RESTIC_REPOSITORY="$BACKUP_REPOSITORY_ID:/$HOSTNAME"
export RESTIC_PASSWORD="$(bw_wrapper get password $BACKUP_REPOSITORY_PW_ID)"

echo "Backing up ${HOME}"
restic backup "$HOME" --exclude-file "$HOME/.config/restic/excludes"
restic forget --keep-daily 7 --keep-weekly 4 --keep-monthly 3 --keep-yearly 1 --prune
