#!/usr/bin/env sh

# Wrapper for startx to run iGPU or dGPU depending on docking station connectivity.
# There is probably a better way to do this.

if [ "$HOSTNAME" == "p51" ]
then
    [ stat "/sys/class/usbmisc"/ ];
    export LAYOUT=dGPU
    /usr/local/bin/nvidia-xrun
else
    /bin/startx
fi
