#!/usr/bin/env sh

# Wrapper for startx to run iGPU or dGPU depending on docking station connectivity.
# There is probably a better way to do this.

stat /sys/class/usbmisc/ > /dev/null 2>&1 && export LAYOUT=dgpu && nvidia-xrun || export LAYOUT=igpu && startx
