#!/bin/env sh

[ $# -eq 0 ] && echo "Please supply a virtual machine name" && exit 1

uuid=/dev/disk/by-uuid/2d24ae98-00c7-437d-a982-1178c6ac76f1

start_cmd(){ virsh start "$1" ;}

[ "$1" = 'V0001' ] && { [ -e $uuid ] && sudo mount $uuid /mnt/portable && start_cmd "$1" && exit 0 ;} || echo "Error mounting or starting VM" && exit 1 

start_cmd "$1"
