#!/bin/env sh

[ "$(amixer sget Mic\ Mute-LED\ Mode | cut -d: -f2 | tr -d ' ' | tail -1)" = Off ] && amixer -q sset Mic\ Mute-LED\ Mode On && exit
amixer -q sset Mic\ Mute-LED\ Mode Off
#[ "$(amixer sget Mic\ Mute-LED\ Mode | cut -d: -f2 | tr -d ' ' | tail -1)" = "'Off'" ] && amixer -q sset Mic\ Mute-LED\ Mode On && exit 0
#amixer -q sset Mic\ Mute-LED\ Mode Off
pactl list short sinks 
pactl list source-outputs
pactl move-sink-input 5 1
pacmd set-default-sink 1

output="alsa_output.pci-0000_07_00.4"
sink=$(pactl list short sinks | rg -o -m1 "($output\..*?)\s" --replace "\$1")
pactl set-default-sink $sink




